<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h1>Bootrap Templates</h1>
        <section class="mt-5">
            <h2>Typography</h2>
            <small class="text-muted">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam, fugiat.</small>
            <p class="lead">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum consequuntur nam ullam, libero facere ad dolore veniam. Autem, totam? Cum.</p>
        </section>
        <section class="mb-5">
            <h2>Blockquote</h2>
            <blockquote class="blockquote">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, ratione.</p>
                <footer class="blockquote-footer">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae, iure!</footer>
            </blockquote>
        </section>
        <section class="mb-5">
            <h2>text emphasis</h2>
            <p class="text-muted">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime, iusto.</p>
            <p class="text-primary">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vero quaerat temporibus aperiam. Possimus, ducimus maxime!</p>
            <p class="text-secondary">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente iure deleniti rerum dolores, quidem nostrum.</p>
            <p class="text-success">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore fuga quae quo cum esse laudantium.</p>
            <p class="text-warning">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque officiis voluptate odio, dicta minima dolorum!</p>
            <p class="text-danger">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut numquam autem dolorum, necessitatibus sed et.</p>
            <p class="text-info">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos quia, eveniet accusantium cum deserunt vel!</p>
        </section>
        <section class="mb-5">
            <h2>text align</h2>
            <p class="text-success text-left">Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus nam exercitationem voluptatum laborum, vel, mollitia ipsam id molestias ratione hic laudantium accusamus rem tenetur soluta animi unde corrupti inventore dignissimos, libero illo natus. Veniam totam eos rerum exercitationem sint quibusdam repellendus quo fugit sequi minus velit provident, in a ratione.</p>
            <p class="text-danger text-center">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, atque commodi quod sint perferendis voluptas ab, asperiores hic voluptatem officia suscipit. Id nihil ipsa iure adipisci. Illo explicabo, doloremque rem non, velit iste fuga excepturi et totam earum, dicta dolore aut. Temporibus magnam praesentium, voluptatem expedita labore id tempora veniam.</p>
            <p class="text-primary text-right">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut, nihil sunt! Voluptate nostrum sequi dolorum a distinctio corporis excepturi porro at quam ad nesciunt, voluptates harum iure commodi amet cumque, consequuntur quas corrupti accusamus dolor dignissimos accusantium doloribus quod? Error, magni ea expedita quasi consectetur nesciunt accusantium harum vero culpa.</p>
        </section>
        <section class="mb-5">
            <h2>buttons</h2>
            <button class="btn-primary">primary</button>
            <button class="btn-secondary">secondary</button>
            <button class="btn-success">success</button>
            <button class="btn-warning">warning</button>
            <button class="btn-danger">danger</button>
            <button class="btn-info">info</button>
        </section>
        <section class="mb-5">
            <h2>Button outline</h2>
            <button class="btn-outline-primary">primary</button>
            <button class="btn-outline-secondary">secondary</button>
            <button class="btn-outline-success">success</button>
            <button class="btn-outline-warning">warning</button>
            <button class="btn-outline-danger">danger</button>
            <button class="btn-outline-info">info</button>
        </section>
        <section class="mb-5">
            <h2>button sizes</h2>
            <button class="btn-primary btn-lg">large</button><br><br>
            <button class="btn-primary">default</button><br><br>
            <button class="btn-primary btn-sm">small</button>
            <br><br>
            <button class="btn-success btn-lg btn-block">block button</button>
        </section>
        <section class="mb-5">
            <h2>button group</h2>
            <div class="btn-group">
                <button class="btn-primary">button</button><button class="btn-primary">button</button><button class="btn-primary">button</button><button class="btn-primary">button</button><button class="btn-primary">button</button>
            </div>
        </section>
        <section class="mb-5">
            <h2>button checkbox</h2>
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label for="" class="btn btn-success active">
                    <input type="checkbox" name="" id="" checked="">
                    checked
                </label>
                <label for="" class="btn btn-success">
                    <input type="checkbox" autocomplete="off">
                    checked
                </label>
                <label for="" class="btn btn-success">
                    <input type="checkbox" autocomplete="off">
                    checked
                </label>
                </div>
        </section>
        <section class="mb-5">
            <h2>Button radio</h2>
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio">
                    radio
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" autocomplete="off">
                    radio
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" autocomplete="off">
                    radio
                </label>
            </div>
        </section>
        <section class="mb-5">
            <h2>table</h2>
            <table class="table table-borderd table-secondary table-hover">
                <thead class="table-dark">
                    <tr>
                        <th>first name</th>
                        <th>last name</th>
                        <th>email</th>
                        <th>gender</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>mcord</td>
                        <td>ordon</td>
                        <td>mcord@yahoo.com</td>
                        <td>male</td>
                    </tr>
                    <tr>
                        <td>jack</td>
                        <td>ordon</td>
                        <td>jackie@gmail.com</td>
                        <td>male</td>
                    </tr>
                    <tr>
                        <td>annie</td>
                        <td>ordon</td>
                        <td>ann@yahoo.com</td>
                        <td>female</td>
                    </tr>
                </tbody>
            </table>
            <table class="table table-borderd table-hover">
                <thead class="table-danger">
                    <tr>
                        <th>first name</th>
                        <th>last name</th>
                        <th>email</th>
                        <th>gender</th>
                    </tr>
                </thead>
                <tbody class="table-success">
                    <tr>
                        <td>mcord</td>
                        <td>ordon</td>
                        <td>mcord@yahoo.com</td>
                        <td>male</td>
                    </tr>
                    <tr>
                        <td>jack</td>
                        <td>ordon</td>
                        <td>jackie@gmail.com</td>
                        <td>male</td>
                    </tr>
                    <tr>
                        <td>annie</td>
                        <td>ordon</td>
                        <td>ann@yahoo.com</td>
                        <td>female</td>
                    </tr>
                </tbody>
            </table>
            <table class="table table-borderd table-hover table-dark">
                <thead>
                    <tr>
                        <th>first name</th>
                        <th>last name</th>
                        <th>email</th>
                        <th>gender</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>mcord</td>
                        <td>ordon</td>
                        <td>mcord@yahoo.com</td>
                        <td>male</td>
                    </tr>
                    <tr>
                        <td>jack</td>
                        <td>ordon</td>
                        <td>jackie@gmail.com</td>
                        <td>male</td>
                    </tr>
                    <tr>
                        <td>annie</td>
                        <td>ordon</td>
                        <td>ann@yahoo.com</td>
                        <td>female</td>
                    </tr>
                </tbody>
            </table>
        </section>
        <section class="mb-5">
            <h2>forms</h2>
            <div class="form-group">
                <label for="">Email Address</label>
                <input type="email" name="" id="" class="form-control" placeholder="enter email">
                <email class="form-text text-muted">enter a valid email</email>
            </div>
            <div class="form-group">
                <label for="">password</label>
                <input type="password" name="" id="" class="form-control" placeholder="enter password">
            </div>
            <div class="form-group">
                <label for="">select</label>
                <select name="" id="" class="form-control">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="">textArea</label>
                <textarea name="" id="" cols="30" rows="10" class="form-control" placeholder="text area">text area</textarea>
            </div>
            <div class="form-group">
                <label for="">Disabled input</label>
                <input type="text" name="" id="" class="form-control disabled">
            </div>
            <div class="form-group">
                <label for="">valid input</label>
                <input type="text" name="" id="" class="form-control is-valid">
                <div class="valid-feedback">success</div>   
            </div>
            <div class="form-group">
                <label for="">invalid input</label>
                <input type="text" name="" id="" class="form-control is-invalid">
                <div class="invalid-feedback">error</div>
            </div>
            <div class="form-group">
                <label for="">large input</label>
                <input type="text" name="" id="" class="form-control form-control-lg" placeholder="large inbox">
            </div>
            <div class="form-group">
                <label for="">small input</label>
                <input type="text" name="" id="" class="form-control form-control-sm" placeholder="small textbox">
            </div>
        </section>
        <section class="mb-5">
            <h2>fieldset</h2>
            <fieldset>
                <legend>custom form elements</legend>
                <div class="form-group">
                    <div class="custom-control custom-radio">
                        <input type="radio" name="customRadio" id="customRadio1" class="custom-control-input" checked="">
                        <label for="customRadio1" class="custom-control-label">Toggle Custom Radio-1</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input type="radio" name="customRadio" id="customRadio2" class="custom-control-input">
                        <label for="customRadio2" class="custom-control-label">Toggle Custom Radio-2</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input type="radio" name="customRadio" id="customRadio3" class="custom-control-input">
                        <label for="customRadio3" class="custom-control-label">Toggle Custom Radio-3</label>
                    </div>
                </div>
                <legend>checkbox</legend>
                <div class="form-group">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" name="customCheckbox" id="customCheckbox1" checked="" class="custom-control-input">
                        <label for="customCheckbox1" class="custom-control-label">custom checkbox</label>    
                    </div>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" name="customCheckbox" id="customCheckbox2" class="custom-control-input">
                        <label for="customCheckbox2" class="custom-control-label">custom checkbox</label>    
                    </div>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" name="customCheckbox" id="customCheckbox3" class="custom-control-input">
                        <label for="customCheckbox3" class="custom-control-label">custom checkbox</label>    
                    </div>
                </div>
                <legend>Switch</legend>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <input type="checkbox" id="customSwitch" class="custom-control-input" checked="">
                        <label for="customSwitch" class="custom-control-label">custom switch</label>
                    </div>
                </div>
            </fieldset>
        </section>
        <section class="mb-5">
            <h3>Tabs</h3>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="#home" class="nav-link active" data-toggle="tab">Home</a>
                </li>
                <li class="nav-item">
                    <a href="#profile" class="nav-link" data-toggle="tab">Profile</a>
                </li>
                <li class="nav-item">
                    <a href="#about" class="nav-link" data-toggle="tab">About</a>
                </li>
                <li class="nav-item">
                    <a href="#contact" class="nav-link" data-toggle="tab">Contact</a>
                </li>
                <li class="nav-item">
                    <a href="#register" class="nav-link" data-toggle="tab">Registered</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade active show" id="home">
                    <h2 class="text-danger">Home</h2>
                    <p class="text-left text-primary">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati eum voluptatem quia maxime omnis aperiam rem ducimus libero corporis deleniti, tempora modi animi suscipit commodi placeat? Distinctio, placeat quidem illo commodi harum ipsum architecto quis at voluptatum saepe itaque, impedit quia nisi asperiores ut suscipit officia odit exercitationem fuga sed.</p>
                </div>
                <div class="tab-pane fade" id="profile">
                    <h2>Profile</h2>
                    <p class="text-center text-success">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae facere et ad perspiciatis? Sequi sed aliquam doloremque eum deserunt! Dolores corrupti quam ducimus unde officia, doloremque perspiciatis magnam sunt deserunt temporibus tenetur rerum aut veniam beatae facilis atque nam porro repellat fuga. Reiciendis labore architecto vel nam commodi itaque adipisci?</p>
                </div>
                <div class="tab-pane fade" id="about">
                   <h2 class="text-warning">Profile</h2>
                   <p class="text-right text-secondary">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat excepturi qui placeat, ipsa saepe sequi voluptas illo mollitia reiciendis sapiente? Neque harum, beatae soluta asperiores fuga nobis optio facere non dolorem, enim magni qui nemo sunt cupiditate. Deleniti voluptatem quos nobis eos, error tempore beatae accusantium ducimus. Natus, beatae impedit?</p>
                </div>
                <div class="tab-pane fade" id="contact">
                    <h2 class="text-info">Registered</h2>
                    <p class="text-left text-danger">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia odit quasi explicabo deleniti rerum consectetur atque nisi ipsa, voluptatum ut. Laborum harum officia nemo soluta quia quas ipsum esse provident, corrupti aliquam explicabo suscipit nulla molestias nostrum, voluptas assumenda nobis cupiditate porro unde? Veniam soluta voluptatum repellat tempora unde doloribus.</p>
                </div>
                <div class="tab-pane fade" id="register">
                    <h2 class="text-secondary">Registered</h2>
                    <p class="text-center text-secondary">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis provident, ex cumque eos animi sequi molestias maxime aliquam explicabo iste ipsam fugit magni et expedita, vel ipsa voluptatum officiis rem natus consequuntur doloremque doloribus esse! Cum, quod? Labore alias eveniet exercitationem modi ea consectetur doloribus amet at pariatur iure fugit eligendi, nesciunt facilis ratione laborum ullam reprehenderit. Veritatis, velit maxime!</p>
                </div>
            </div>
        </section>
        <section class="mb-5">
            <h2>Alert</h2>
            <div class="alert alert-primary">
                <h4 class="alert-heading">Primary</h4>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quaerat similique qui eius, perferendis assumenda cum magni unde ex adipisci aliquid?</p>
            </div>
            <div class="alert alert-secondary">
                <h4 class="alert-heading">Secondary</h4>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quaerat similique qui eius, perferendis assumenda cum magni unde ex adipisci aliquid?</p>
            </div>
            <div class="alert alert-success">
                <h4 class="alert-heading">Success</h4>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quaerat similique qui eius, perferendis assumenda cum magni unde ex adipisci aliquid?</p>
            </div>
            <div class="alert alert-warning">
                <h4 class="alert-heading">Warning</h4>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quaerat similique qui eius, perferendis assumenda cum magni unde ex adipisci aliquid?</p>
            </div>
            <div class="alert alert-danger">
                <h4 class="alert-heading">Danger</h4>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quaerat similique qui eius, perferendis assumenda cum magni unde ex adipisci aliquid?</p>
            </div>
            <div class="alert alert-info">
                <h4 class="alert-heading">Info</h4>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quaerat similique qui eius, perferendis assumenda cum magni unde ex adipisci aliquid?</p>
            </div>
        </section>
        <section class="mb-5">
            <h2>Alert</h2>
            <div class="alert alert-dismissible alert-warning">
                <button type="submit" class="close" data-dismiss="alert">&times;</button>
                <h4 class="alert-heading">warning</h4>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eius at quisquam sequi rerum delectus dolorem quos ab id iure et!</p>
            </div>
        </section>
        <section class="mb-5">
            <h2>Badges</h2>
            <span class="badge badge-primary">Primary</span>
            <span class="badge badge-secondary">secondary</span>
            <span class="badge badge-success">success</span>
            <span class="badge badge-warning">warning</span>
            <span class="badge badge-danger">danger</span>
            <span class="badge badge-info">info</span>
        </section>
        <section class="mb-5">
            <h2>Progress Bars</h2>
            <div class="progress mb-5">
                <div class="progress-bar bg-success" style="width: 25%" area-valuemax="100">25%</div>
            </div>
            <div class="progress mb-5">
                <div class="progress-bar bg-primary" style="width:50%" area-valuemax="100">50%</div>
            </div>
            <div class="progress mb-5">
                <div class="progress-bar bg-danger" style="width:75%" area-valuemax="100">75%</div>
            </div>
            <div class="progress mb-5">
                <div class="progress-bar lg-warning" style="width:100%" area-valuemax="100">100%</div>
            </div>
        </section>
        <section class="mb-5">
            <div class="jumbotron">
                <h1>Hello Home</h1>
                <p class="lead text-success">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, eius illo velit quaerat consectetur sapiente suscipit minus itaque repellat esse. Ea amet ut necessitatibus alias reprehenderit expedita, animi placeat maxime hic architecto impedit? Corporis ipsa, fugiat tempora aliquam quam ea voluptatum exercitationem sunt tempore veniam saepe repellendus libero recusandae ducimus sequi minima. Quasi, nobis dolorum nihil quia itaque laudantium aperiam.</p>
            </div>
        </section>
        <section class="mb-5 bg-secondary">
            <h2 class="text-success">list group</h2>
            <a href="#" class="list-group-item list-group-item-action active bg-secondary">Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, fugit.</a>
            <a href="#" class="list-group-item list-group-item-action active text-warning bg-secondary">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptas quam quaerat itaque omnis cum repellendus accusantium et molestiae nostrum vitae!</a>
            <a href="#" class="list-group-item list-group-item-action active text-success bg-secondary">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium dolorem unde excepturi a reprehenderit minus ex iure laboriosam amet deleniti.</a>
            <a href="#" class="list-group-item list-group-item-action active bg-secondary text-primary">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque quis deserunt quod architecto et aspernatur laboriosam ipsa doloribus, accusantium placeat?</a>
            <a href="" class="list-group-item list-group-item-action active bg-success text-danger">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis quibusdam, provident libero dicta quasi dolore aperiam adipisci asperiores. Quasi, magnam?</a>
        </section>
        <section class="mb-5">
            <h2>Cards</h2>
            <div class="card mb-3 bg-success" style="max-width:20rem;">
                <div class="card-header bg-primary">Header</div>
                <div class="card-body">
                    <h4 class="card-title">Card Title</h4>
                    <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, tempora.</p>
                </div>
            </div>
            <div class="card mb-3 bg-primary" style="max-width:20rem;">
                <div class="card-header bg-secondary">Header Card Sample</div>
                <div class="card-body">
                    <h4 class="card-title">Card Title Sample</h4>
                    <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, tempora.</p>
                </div>
            </div>
            <div class="card mb-3 bg-secondary" style="max-width:20rem;">
                <div class="card-header bg-warning">Header Card Sample Images</div>
                <div class="card-body">
                    <h4 class="card-title">Card Title Images</h4>
                    <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, tempora.</p>
                </div>
            </div>
        </section>
        <section class="mb-5">
            <h2>Dialog-Popover</h2>
            <button type="button" class="btn btn-secondary" title="left" data-container="Body" data-toggle="popover" data-palcement="left" data-content="four score and seven years ago our father brouth for as this continent a new nation">text-left</button>
            <button type="button" class="btn btn-secondary" title="top" data-container="Body" data-toggle="popover" data-palcement="top" data-content="four score and seven years ago our father brouth for as this continent a new nation">text-top</button>
            <button type="button" class="btn btn-secondary" title="right" data-container="Body" data-toggle="popover" data-palcement="right" data-content="four score and seven years ago our father brouth for as this continent a new nation">text-right</button>
            <button type="button" class="btn btn-secondary" title="bottom" data-container="Body" data-toggle="popover" data-palcement="bottom" data-content="four score and seven years ago our father brouth for as this continent a new nation">text-bottom</button>
        </section>
        <section class="mb-5">
            <h2>Dialog Toltip</h2>
            <button type="button" class="btn btn-primary" data-original-title="The Lord is my Sheppered i shall not one he maketh me to lie down in green pasture, he leads me in the path of righteousness for his name sake" data-toggle="tooltip" data-palcement="top">top</button>
            <button type="button" class="btn btn-primary" data-original-title="Four score and seven years ago our father brougth for as this continenth a new nation on any nation so concieve and so dedicated to the preposition that all men ARE created equal" data-toggle="tooltip" data-palcement="bottom">bottom</button>
            <button type="button" class="btn btn-primary" data-original-title="ther something to leave a life of a person that we can" data-toggle="tooltip" data-palcement="left">left</button>
            <button type="button" class="btn btn-primary" data-original-title="tooltip right" data-toggle="tooltip" data-palcement="right">right</button>
        </section>
        <section class="mb-5">
            <h2>Modal</h2>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Show Modal</button>
            <div class="modal fade" id="exampleModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <div class="modal-title">modal title</div>
                            <button type="button" data-dismiss="modal" area-label="close" class="close">&times;</button>
                        </div>
                        <div class="modal-body">
                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum sed laboriosam illo vitae repellat, non quasi hic dolorum voluptas tempore?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary">Save Change</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close Modal</button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="mb-5">
            <h2>Grid System</h2>
            <div class="container">
                <div class="row bg-secondary">
                    <div class="col-sm bg-light border m-1 p-5">col-1</div>
                    <div class="col-sm bg-light border m-1 p-5">col-1</div>
                    <div class="col-sm bg-light border m-1 p-5">col-1</div>
                    <div class="col-sm bg-light border m-1 p-5">col-1</div>
                </div>
                <div class="row bg-primary">
                    <div class="col bg-light border m-1 p3">Colunm-1</div>
                    <div class="col bg-light border m-1 p3">Colunm-2</div>
                    <div class="col bg-light border m-1 p3">Colunm-3</div>
                    <div class="col bg-light border m-1 p3">Colunm-4</div>
                </div>
            </div>
            <div class="row bg-success">
                <div class="col-lg-4 bg-light m-1 p-5">Colunm-1</div>
                <div class="col-lg-4 bg-light m-1 p-5">Colunm-2</div>
                    <div class="col-lg-4 bg-light m-1 p-5">Colunm-3</div>
                    <div class="col-lg-4 bg-light m-1 p-5">Colunm-4</div>
                    <div class="col-lg-4 bg-light m-1 p-5">Colunm-5</div>
            </div>
        </section>
    </div>  
    <div style="max-width: 23px;"></div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   <script>
    $(function () {
        $('[data-toggle="popover"]').popover();
        $('[data-toggle="tooltip"]').tooltip();
    }); 
   </script>
</body>
</html>

